services:
  - type: web
    name: selection-project2
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT banuhnm:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
